# Generated by Django 2.2.4 on 2019-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('gender_catagory', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=5)),
                ('catagory', models.CharField(max_length=50)),
                ('sub_catagory', models.CharField(max_length=50)),
                ('price', models.IntegerField(default='0')),
                ('publish_date', models.DateField()),
                ('quantity', models.IntegerField(default='1')),
                ('Brand', models.CharField(max_length=50)),
            ],
        ),
    ]
