# Generated by Django 2.2.4 on 2019-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default='0'),
        ),
    ]
